name: universal-ctags

on:
  push:
    paths:
      - 'dev/nix/ctags.nix'
    branches:
        - 'main'
  pull_request:
    paths:
      - 'dev/nix/ctags.nix'
  workflow_dispatch:
permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  x86_64-linux:
    name: Build ctags x86_64-linux
    runs-on: blacksmith
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@07b8bcba1b22d847db7ee507180c33e115499665 # SECURITY: pin third-party action hashes # SECURITY: pin third-party action hashes
      - uses: useblacksmith/magic-nix-cache-action@v1
      - name: Run `nix build`
        run: |
          nix build .#ctags
      - name: Rename an prepare for upload
        run: |
          mkdir -p dist
          cp -R -L ./result/bin/universal-ctags-* dist/
          cd dist/ && ls | xargs -I{} mv {} "{}.$(git rev-parse --short HEAD)"
      - name: Show hash of ctags
        run: |
          shasum -a 256 ./dist/universal-ctags-*
